export type TaskRole =
  | "data_entry_tech"
  | "pv2_tech"
  | "delivery_tech"
  | "pharmacist"
  | "director"
  | "all_staff";

export type TaskFrequency = "daily" | "weekly" | "monthly" | "quarterly";

export type TaskCategory = "achc" | "state_board" | "retention" | "operations";

export interface PharmacyTask {
  id: string;
  title: string;
  description?: string;
  role: TaskRole;
  frequency: TaskFrequency;
  category: TaskCategory;
  taskGroup: string;
  isUrgent?: boolean;
}

export interface Site {
  id: string;
  name: string;
  region: string;
}

export const SITES: Site[] = [
  { id: "1417", name: "RX Pike Street", region: "Seattle, WA" },
  { id: "1842", name: "RX Hollywood Flagship", region: "Los Angeles, CA" },
  { id: "2031", name: "RX Oakland", region: "Oakland, CA" },
];

export const CATEGORY_CONFIG: Record<
  TaskCategory,
  { label: string; color: string; bg: string; badge: string; dot: string }
> = {
  operations: {
    label: "Operations",
    color: "text-slate-700",
    bg: "bg-slate-50",
    badge: "bg-slate-100 text-slate-600",
    dot: "bg-slate-400",
  },
  achc: {
    label: "ACHC Compliance",
    color: "text-blue-700",
    bg: "bg-blue-50",
    badge: "bg-blue-100 text-blue-700",
    dot: "bg-blue-500",
  },
  state_board: {
    label: "State Board",
    color: "text-emerald-700",
    bg: "bg-emerald-50",
    badge: "bg-emerald-100 text-emerald-700",
    dot: "bg-emerald-500",
  },
  retention: {
    label: "Retention Metrics",
    color: "text-amber-700",
    bg: "bg-amber-50",
    badge: "bg-amber-100 text-amber-700",
    dot: "bg-amber-500",
  },
};

export const ROLE_CONFIG: Record<
  Exclude<TaskRole, "all_staff">,
  { label: string; short: string; color: string }
> = {
  data_entry_tech: { label: "Data Entry Technician", short: "DE Tech", color: "text-violet-700" },
  pv2_tech: { label: "PV2 Technician", short: "PV2 Tech", color: "text-blue-700" },
  delivery_tech: { label: "Delivery Technician", short: "Delivery Tech", color: "text-cyan-700" },
  pharmacist: { label: "Pharmacist", short: "Pharmacist", color: "text-purple-700" },
  director: { label: "Site Director", short: "Director", color: "text-rose-700" },
};

/** Display order for role sections in the new role-based view.
 *  `all_staff` is intentionally excluded — those tasks are folded
 *  into each applicable role section rather than shown separately. */
export const ROLE_ORDER: TaskRole[] = [
  "data_entry_tech",
  "pv2_tech",
  "delivery_tech",
  "pharmacist",
  "director",
];

/** Ordered task-group names within each role.
 *  "Team Huddle" is listed last in every role so that folded
 *  all_staff tasks always appear at the bottom of any role section. */
export const ROLE_GROUP_ORDER: Partial<Record<TaskRole, string[]>> = {
  data_entry_tech: [
    "Contact Manager",
    "ICQ",
    "Data Entry",
    "Adjudication Exception",
    "Support Other Roles",
    "Team Huddle",
  ],
  pv2_tech: [
    "CRC & Order Review",
    "Dispensing & Copay",
    "Patient Retention",
    "Digital & In-Store",
    "Weekly Purchase",
    "Team Huddle",
  ],
  delivery_tech: [
    "Opening & Compliance",
    "Package Management",
    "Delivery Setup",
    "Invoicing & Reports",
    "Closing",
    "Weekly",
    "Team Huddle",
  ],
  pharmacist: [
    "Shift Sign-In",
    "Central Fulfillment",
    "Voicemail & Emails",
    "PV1 / PIKE",
    "Pharmacy Orders",
    "Shift Sign-Out",
    "Weekly",
    "Monthly & Quarterly",
    "Team Huddle",
  ],
  director: [
    "Daily",
    "Weekly",
    "Monthly",
    "Quarterly",
    "Team Huddle",
  ],
};

export const TASKS: PharmacyTask[] = [
  // ── DATA ENTRY TECH · DAILY ─────────────────────────────────────────────
  {
    id: "de-d-001",
    title: "Clear 'Reply Received' in Contact Manager",
    description: "Notify patients of refill denials and mark on CPS priority comments med list.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Contact Manager",
    isUrgent: true,
  },
  {
    id: "de-d-002",
    title: "Work through 'Phone' contact method",
    description: "Resend requests as needed or call prescriber office for unresolved items.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Contact Manager",
  },
  {
    id: "de-d-009",
    title: "Respond to ClerkChat patient messages",
    description: "Review and respond to incoming patient messages in ClerkChat. Resolve open requests and escalate clinical questions to the pharmacist.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Contact Manager",
  },
  {
    id: "de-d-003",
    title: "Sort through ICQ queue",
    description: "Process new prescriptions, refill responses, PSAs, and transferred prescriptions.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "ICQ",
    isUrgent: true,
  },
  {
    id: "de-d-004",
    title: "Work through DE queue",
    description: "Prioritize by promise time (top to bottom), push through adjudication to DUR/PV1. Notify patients for billing issues.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Data Entry",
  },
  {
    id: "de-d-005",
    title: "Process new prescriptions",
    description: "Notify patient of billing issues, consider sync fill for chronic meds, make note on CPS priority comments. Keep delivery as CONTACT PT.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Data Entry",
  },
  {
    id: "de-d-006",
    title: "New patient profile setup",
    description: "Reach out to new patients: patient info tab, allergies, insurance, PCCSA. Add to Eagle, address billing, add IA/PCCSA alert, transfer to RPh for consult.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Data Entry",
  },
  {
    id: "de-d-007",
    title: "Resolve Adjudication Exceptions",
    description: "Clear all remaining adjudication exceptions and notify patients as needed.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Adjudication Exception",
  },
  {
    id: "de-d-008",
    title: "Support other pharmacy staff",
    description: "Assist other techs with DE, PV2, DP, CM, ICQ tasks as needed.",
    role: "data_entry_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Support Other Roles",
  },

  // ── PV2 TECH · DAILY ────────────────────────────────────────────────────
  {
    id: "pv2-d-001",
    title: "Respond to / resolve CRC emails (kickbacks)",
    description: "Address CRC email kickbacks and reprocess rejected orders.",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "CRC & Order Review",
    isUrgent: true,
  },
  {
    id: "pv2-d-002",
    title: "Filter and review orders by delivery method",
    description: "Sort by will call, FedEx/USPS, driver — omit CONTACT PT/PA submitted. Review for completeness and merge split orders.",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "CRC & Order Review",
  },
  {
    id: "pv2-d-003",
    title: "Check CPS priority comments for each order",
    description: "Confirm packaging/delivery method and note any temp address changes.",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "CRC & Order Review",
  },
  {
    id: "pv2-d-004",
    title: "Push DE/Adj Exc items — message RPh for DUR/PV1",
    description: "For each order, push items in DE or Adj Exc and message RPh for clinical review.",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "CRC & Order Review",
  },
  {
    id: "pv2-d-005",
    title: "Complete final NDC check",
    description: "Verify correct NDC for each prescription before dispensing.",
    role: "pv2_tech",
    frequency: "daily",
    category: "state_board",
    taskGroup: "Dispensing & Copay",
  },
  {
    id: "pv2-d-006",
    title: "Check and confirm copays",
    description: "Call patients for new CC info if copay is new. Add to Eagle, leave AR note (ok to autocharge, call before, etc.).",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Dispensing & Copay",
  },
  {
    id: "pv2-d-007",
    title: "Verify all orders reach 'Submitted' status in F3",
    description: "After PV2, confirm all meds updated to 'submitted' in F3. Decline and reprocess if any fall into prod disp.",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Dispensing & Copay",
  },
  {
    id: "pv2-d-008",
    title: "Check 35-day report",
    description: "Review patient profiles for stale unprocessed prescriptions. Call patients or process orders. Confirm ERP enrollment.",
    role: "pv2_tech",
    frequency: "daily",
    category: "retention",
    taskGroup: "Patient Retention",
  },
  {
    id: "pv2-d-009",
    title: "Address Contact Manager orders",
    description: "Handle orders in CM — take to PV2 if reply received. Follow up with patient or MD office for pending refills.",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Patient Retention",
  },
  {
    id: "pv2-d-010",
    title: "Clear ERP prescription rejections",
    description: "Resolve ERP prescription rejections and notify patients as needed.",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Patient Retention",
  },
  {
    id: "pv2-d-011",
    title: "Fill waiter and in-store orders",
    description: "Dispense products for waiter and in-store product dispensing queue.",
    role: "pv2_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Digital & In-Store",
  },

  // ── DELIVERY TECH · DAILY ───────────────────────────────────────────────
  {
    id: "del-d-001",
    title: "Open register",
    description: "Perform opening register procedures.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Opening & Compliance",
    isUrgent: true,
  },
  {
    id: "del-d-002",
    title: "Log refrigerator and freezer temperatures",
    description: "Record fridge and freezer temps on the Temp Log Clipboard.",
    role: "delivery_tech",
    frequency: "daily",
    category: "achc",
    taskGroup: "Opening & Compliance",
    isUrgent: true,
  },
  {
    id: "del-d-003",
    title: "Log humidity levels",
    description: "Record ambient humidity on the Temp Log Clipboard.",
    role: "delivery_tech",
    frequency: "daily",
    category: "achc",
    taskGroup: "Opening & Compliance",
  },
  {
    id: "del-d-004",
    title: "Confirm central fulfillment packages received",
    description: "Compare received packages against the manifest. Sort by will call vs. delivery.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Package Management",
    isUrgent: true,
  },
  {
    id: "del-d-005",
    title: "Check in CRC orders in CF Queue",
    description: "Check in all CRC orders and merge packages as needed.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Package Management",
  },
  {
    id: "del-d-006",
    title: "Contact patients for will-call pick-up",
    description: "Call/text patients for pick-up orders. Write RTS date (14 days from billed) and first contact date on packages.",
    role: "delivery_tech",
    frequency: "daily",
    category: "retention",
    taskGroup: "Delivery Setup",
  },
  {
    id: "del-d-007",
    title: "Set up PSL deliveries before scheduled cutoff",
    description: "Pack and prepare all PSL delivery orders by the designated AM cutoff.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Delivery Setup",
    isUrgent: true,
  },
  {
    id: "del-d-008",
    title: "Set up FedEx/USPS orders by 1:30 PM",
    description: "Pack and ship FedEx/USPS orders before the 1:30 PM cutoff.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Delivery Setup",
    isUrgent: true,
  },
  {
    id: "del-d-009",
    title: "Set up driver delivery routes",
    description: "Verify complete orders in MCK, note alternative phone numbers, check copay/priority notes, and follow driver delivery guide.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Delivery Setup",
  },
  {
    id: "del-d-010",
    title: "Confirm Cardinal invoice and MCK purchase order",
    description: "Verify all items received match the invoice. Document any discrepancies and check in Cardinal order.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Invoicing & Reports",
  },
  {
    id: "del-d-011",
    title: "AR Report review",
    description: "Check copay billing accuracy, bill CCOF if applicable, reach out to patients for outstanding balances.",
    role: "delivery_tech",
    frequency: "daily",
    category: "retention",
    taskGroup: "Invoicing & Reports",
  },
  {
    id: "del-d-012",
    title: "RX Not Scanned Report",
    description: "Run BI portal report (Pharmacy > RX Not Scanned in Eagle POS). Scan and charge barcodes in POS. Collect payment or AR-bin if unable.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Invoicing & Reports",
  },
  {
    id: "del-d-013",
    title: "Waiting in Bin Report",
    description: "Run Core Reports > Waiting in Bin (Days=7). Send reminder calls/texts to patients.",
    role: "delivery_tech",
    frequency: "daily",
    category: "retention",
    taskGroup: "Invoicing & Reports",
  },
  {
    id: "del-d-014",
    title: "Return to Stock processing",
    description: "Run RTS report (Tools > Rx Tools > Return to Stock). Pull unclaimed meds, print RTS labels, complete return to stock.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Invoicing & Reports",
  },
  {
    id: "del-d-015",
    title: "Close the register",
    description: "Perform end-of-day register closing and balancing procedures.",
    role: "delivery_tech",
    frequency: "daily",
    category: "operations",
    taskGroup: "Closing",
  },

  // ── PHARMACIST · DAILY ──────────────────────────────────────────────────
  {
    id: "rph-d-001",
    title: "Sign pharmacist signature log (morning)",
    description: "Sign in to the pharmacist signature log at start of shift.",
    role: "pharmacist",
    frequency: "daily",
    category: "state_board",
    taskGroup: "Shift Sign-In",
    isUrgent: true,
  },
  {
    id: "rph-d-002",
    title: "Scan central fulfillment queue for past-due orders",
    description: "Check for past-due or missing orders not crossed to CoreFlex/CRC.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Central Fulfillment",
    isUrgent: true,
  },
  {
    id: "rph-d-003",
    title: "Release orders via order grouping scan",
    description: "Scan order grouping to release all pending orders.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Central Fulfillment",
    isUrgent: true,
  },
  {
    id: "rph-d-004",
    title: "Snip morning inventory slips to adherence pack/CRC chat",
    description: "Communicate morning inventory slips to adherence pack and CRC coordination chat.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Central Fulfillment",
  },
  {
    id: "rph-d-005",
    title: "Voicemail retrieval (overnight / before 11 AM)",
    description: "Check and respond to all overnight voicemails before 11 AM.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Voicemail & Emails",
  },
  {
    id: "rph-d-006",
    title: "CRC clinical review emails (overnight)",
    description: "Review and respond to CRC clinical review emails received overnight.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Voicemail & Emails",
  },
  {
    id: "rph-d-007",
    title: "PV1 / check URGENT P4H orders",
    description: "Complete pharmacist verification for all urgent P4H orders.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "PV1 / PIKE",
    isUrgent: true,
  },
  {
    id: "rph-d-008",
    title: "Designated RPh — PV1 PIKE scripts",
    description: "Complete PV1 pharmacist verification for PIKE prescriptions as designated RPh.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "PV1 / PIKE",
  },
  {
    id: "rph-d-009",
    title: "PIKE RPh review chat issues",
    description: "Address DUR rejects, Rx clarification, and therapy duplication issues in PIKE chat.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "PV1 / PIKE",
  },
  {
    id: "rph-d-010",
    title: "PIKE consults (new scripts / new non-waiter patients)",
    description: "Complete pharmacist consultations for new PIKE prescriptions and patients.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "PV1 / PIKE",
  },
  {
    id: "rph-d-011",
    title: "Non-urgent pharmacist product verification",
    description: "Complete product verification (PV) for all non-urgent/routine prescriptions.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "PV1 / PIKE",
  },
  {
    id: "rph-d-012",
    title: "Ensure pharmacy order submitted by 5:30 PM",
    description: "Scan queues for waiters not in product dispensing. Submit pharmacy order before 5:30 PM.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Pharmacy Orders",
    isUrgent: true,
  },
  {
    id: "rph-d-013",
    title: "Check Supply Logix by 5 PM",
    description: "Review Supply Logix for outstanding orders or supply issues before 5 PM.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Pharmacy Orders",
    isUrgent: true,
  },
  {
    id: "rph-d-014",
    title: "Check URGENT PIKE PV1 orders (waiter, must mail)",
    description: "Prioritize and address urgent PIKE orders flagged as waiter or must-mail.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "PV1 / PIKE",
    isUrgent: true,
  },
  {
    id: "rph-d-015",
    title: "Complete URGENT PIKE pharmacist product verification",
    description: "Perform pharmacist product verification for urgent PIKE prescriptions.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "PV1 / PIKE",
    isUrgent: true,
  },
  {
    id: "rph-d-016",
    title: "Voicemail retrieval (12 PM – 6:30 PM)",
    description: "Check and respond to afternoon voicemails between 12 PM and 6:30 PM.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Voicemail & Emails",
  },
  {
    id: "rph-d-017",
    title: "CRC clinical review emails (business hours)",
    description: "Review and respond to CRC clinical review emails during business hours.",
    role: "pharmacist",
    frequency: "daily",
    category: "operations",
    taskGroup: "Voicemail & Emails",
  },
  {
    id: "rph-d-018",
    title: "Sign out pharmacist signature log (end of day)",
    description: "Sign out of pharmacist signature log at end of shift.",
    role: "pharmacist",
    frequency: "daily",
    category: "state_board",
    taskGroup: "Shift Sign-Out",
  },

  // ── DIRECTOR · DAILY ────────────────────────────────────────────────────
  {
    id: "dir-d-001",
    title: "Review daily staffing coverage",
    description: "Confirm all positions are covered and address any gaps or callouts.",
    role: "director",
    frequency: "daily",
    category: "operations",
    taskGroup: "Daily",
    isUrgent: true,
  },
  {
    id: "dir-d-002",
    title: "Morning team briefing / stand-up",
    description: "Lead or facilitate morning team stand-up to communicate priorities and issues.",
    role: "director",
    frequency: "daily",
    category: "operations",
    taskGroup: "Daily",
  },
  {
    id: "dir-d-003",
    title: "Review outstanding patient AR issues",
    description: "Review accounts receivable issues requiring director approval or escalation.",
    role: "director",
    frequency: "daily",
    category: "retention",
    taskGroup: "Daily",
  },

  // ── WEEKLY TASKS ────────────────────────────────────────────────────────
  {
    id: "del-w-001",
    title: "Brinks cash deposit",
    description: "Complete Brinks deposit every Monday and on the last business day of the month.",
    role: "delivery_tech",
    frequency: "weekly",
    category: "operations",
    taskGroup: "Weekly",
  },
  {
    id: "pv2-w-001",
    title: "Submit weekly purchase order (inventory)",
    description: "Review inventory levels and submit PO for the upcoming week.",
    role: "pv2_tech",
    frequency: "weekly",
    category: "operations",
    taskGroup: "Weekly Purchase",
  },
  {
    id: "rph-w-001",
    title: "MTM patient outreach review",
    description: "Review patients eligible for Medication Therapy Management and complete or schedule MTM appointments.",
    role: "pharmacist",
    frequency: "weekly",
    category: "retention",
    taskGroup: "Weekly",
  },
  {
    id: "rph-w-002",
    title: "Adherence packaging and dispensing audit",
    description: "Audit adherence packaging for accuracy, completeness, and proper labeling compliance.",
    role: "pharmacist",
    frequency: "weekly",
    category: "achc",
    taskGroup: "Weekly",
  },
  {
    id: "dir-w-001",
    title: "Weekly performance metrics review",
    description: "Review fill rates, turnaround times, AR aging, and other key KPIs for the week.",
    role: "director",
    frequency: "weekly",
    category: "operations",
    taskGroup: "Weekly",
  },
  {
    id: "dir-w-002",
    title: "Staff communications and escalation follow-up",
    description: "Follow up on all open communications, escalations, and staff issues from the week.",
    role: "director",
    frequency: "weekly",
    category: "operations",
    taskGroup: "Weekly",
  },
  {
    id: "dir-w-003",
    title: "Risk retention report review",
    description: "Review the risk retention report to identify patients at risk of disengaging from care.",
    role: "director",
    frequency: "weekly",
    category: "retention",
    taskGroup: "Weekly",
  },
  {
    id: "all-w-001",
    title: "Weekly team huddle participation",
    description: "Attend or lead the weekly pharmacy staff team huddle.",
    role: "all_staff",
    frequency: "weekly",
    category: "operations",
    taskGroup: "Team Huddle",
  },

  // ── MONTHLY TASKS ───────────────────────────────────────────────────────
  // ACHC
  {
    id: "achc-m-001",
    title: "Patient rights documentation review",
    description: "Review and ensure all patient rights documentation is current, accessible, and properly distributed to patients.",
    role: "director",
    frequency: "monthly",
    category: "achc",
    taskGroup: "Monthly",
  },
  {
    id: "achc-m-002",
    title: "Adverse event and incident reporting review",
    description: "Review all adverse events and incidents reported during the month. Ensure proper documentation and corrective actions.",
    role: "director",
    frequency: "monthly",
    category: "achc",
    taskGroup: "Monthly",
  },
  {
    id: "achc-m-003",
    title: "Policy & procedure manual review",
    description: "Review and update applicable policies and procedures. Ensure staff have acknowledged any updates.",
    role: "director",
    frequency: "monthly",
    category: "achc",
    taskGroup: "Monthly",
  },
  {
    id: "achc-m-004",
    title: "Medication storage and temperature log audit",
    description: "Audit all temperature logs for completeness and excursions. Verify medication storage conditions were maintained throughout the month.",
    role: "director",
    frequency: "monthly",
    category: "achc",
    taskGroup: "Monthly",
  },
  {
    id: "achc-m-005",
    title: "Staff competency documentation review",
    description: "Verify all staff competency records are current and on file.",
    role: "director",
    frequency: "monthly",
    category: "achc",
    taskGroup: "Monthly",
  },
  // State Board
  {
    id: "sb-m-001",
    title: "Pharmacy and staff license status verification",
    description: "Verify pharmacy license and all pharmacist/tech licenses are active. Note upcoming renewal dates.",
    role: "director",
    frequency: "monthly",
    category: "state_board",
    taskGroup: "Monthly",
  },
  {
    id: "sb-m-002",
    title: "DEA compliance and controlled substance audit",
    description: "Perform controlled substance inventory count and verify records match DEA logs.",
    role: "director",
    frequency: "monthly",
    category: "state_board",
    taskGroup: "Monthly",
  },
  {
    id: "sb-m-003",
    title: "Drug storage and security compliance check",
    description: "Inspect drug storage areas, security measures, and confirm compliance with state board regulations.",
    role: "director",
    frequency: "monthly",
    category: "state_board",
    taskGroup: "Monthly",
  },
  // Retention
  {
    id: "ret-m-001",
    title: "Appointment and retention metrics report",
    description: "Run and review the monthly appointment/pickup report. Identify patients with missed or late pickups.",
    role: "director",
    frequency: "monthly",
    category: "retention",
    taskGroup: "Monthly",
  },
  {
    id: "ret-m-002",
    title: "Appointment no-show analysis and follow-up",
    description: "Analyze no-show patterns and confirm follow-up outreach was completed for all missed appointments.",
    role: "director",
    frequency: "monthly",
    category: "retention",
    taskGroup: "Monthly",
  },
  {
    id: "ret-m-003",
    title: "MTM billing and documentation audit",
    description: "Audit MTM billing for accuracy and ensure documentation meets all payer requirements.",
    role: "pharmacist",
    frequency: "monthly",
    category: "retention",
    taskGroup: "Monthly & Quarterly",
  },
  {
    id: "ret-m-004",
    title: "Patient satisfaction survey distribution",
    description: "Distribute monthly patient satisfaction surveys and track response rates.",
    role: "director",
    frequency: "monthly",
    category: "retention",
    taskGroup: "Monthly",
  },
  // Operations
  {
    id: "ops-m-001",
    title: "Submit next month's staffing coverage schedule",
    description: "Prepare and submit the staffing schedule for the upcoming month. Due by the end of the first week of the prior month — e.g., April's schedule is due by the end of the first week of March. Ensure all shifts are covered, including backup coverage for anticipated PTO.",
    role: "director",
    frequency: "monthly",
    category: "operations",
    taskGroup: "Monthly",
  },

  // ── QUARTERLY TASKS ─────────────────────────────────────────────────────
  // ACHC
  {
    id: "achc-q-001",
    title: "Mock ACHC survey preparation",
    description: "Conduct an internal mock ACHC survey to identify compliance gaps before formal accreditation review.",
    role: "director",
    frequency: "quarterly",
    category: "achc",
    taskGroup: "Quarterly",
  },
  {
    id: "achc-q-002",
    title: "ACHC corrective action plans review",
    description: "Review the status of all outstanding corrective action plans from previous ACHC findings.",
    role: "director",
    frequency: "quarterly",
    category: "achc",
    taskGroup: "Quarterly",
  },
  {
    id: "achc-q-003",
    title: "ACHC accreditation document updates",
    description: "Update all ACHC-required accreditation documents and confirm current versions are on file.",
    role: "director",
    frequency: "quarterly",
    category: "achc",
    taskGroup: "Quarterly",
  },
  {
    id: "achc-q-004",
    title: "Pharmacy staff competency assessments",
    description: "Complete formal quarterly competency assessments for all pharmacy staff members.",
    role: "director",
    frequency: "quarterly",
    category: "achc",
    taskGroup: "Quarterly",
  },
  {
    id: "achc-q-005",
    title: "Conduct CQI meeting",
    description: "Facilitate the quarterly Continuous Quality Improvement (CQI) meeting. Prepare agenda covering adverse events, medication errors, patient outcomes, and process gaps identified since the last meeting. Document all attendees, discussion points, and assigned action items with target resolution dates. File meeting minutes per ACHC accreditation requirements.",
    role: "director",
    frequency: "quarterly",
    category: "achc",
    taskGroup: "Quarterly",
  },
  // State Board
  {
    id: "sb-q-001",
    title: "State pharmacy law updates review",
    description: "Review recent updates to state pharmacy laws and communicate relevant changes to staff.",
    role: "director",
    frequency: "quarterly",
    category: "state_board",
    taskGroup: "Quarterly",
  },
  {
    id: "sb-q-002",
    title: "Facility inspection readiness assessment",
    description: "Conduct an internal inspection walkthrough to prepare for potential state board inspection.",
    role: "director",
    frequency: "quarterly",
    category: "state_board",
    taskGroup: "Quarterly",
  },
  {
    id: "sb-q-003",
    title: "Pharmacist CE credit tracking",
    description: "Verify all pharmacists have adequate continuing education credits on file for license renewal.",
    role: "director",
    frequency: "quarterly",
    category: "state_board",
    taskGroup: "Quarterly",
  },
  // Retention
  {
    id: "ret-q-001",
    title: "Quarterly retention program effectiveness review",
    description: "Analyze quarterly retention metrics, compare to benchmarks, and identify improvement opportunities.",
    role: "director",
    frequency: "quarterly",
    category: "retention",
    taskGroup: "Quarterly",
  },
  {
    id: "ret-q-002",
    title: "Formulary access and prior authorization barrier review",
    description: "Review recurring PA denial patterns and formulary access issues impacting patient care continuity.",
    role: "director",
    frequency: "quarterly",
    category: "retention",
    taskGroup: "Quarterly",
  },
  {
    id: "ret-q-003",
    title: "Outcome measures reporting",
    description: "Compile and submit required outcome measures reports to relevant stakeholders and accrediting bodies.",
    role: "director",
    frequency: "quarterly",
    category: "retention",
    taskGroup: "Quarterly",
  },
  {
    id: "ret-q-004",
    title: "Quarterly patient outcomes review",
    description: "Review aggregate patient outcomes including viral load trends, adherence rates, and clinical markers.",
    role: "pharmacist",
    frequency: "quarterly",
    category: "retention",
    taskGroup: "Monthly & Quarterly",
  },
];
