import { useState, useEffect, useRef, useMemo } from "react";
import { useAuth } from "@/App";
import { getUserProfile, isRegionalOrAbove, isDirectorRole, isTechRole, getRoleLabel, getStoreStaff, type StoreStaffMember } from "@/lib/userProfile";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { getCurrentQuarter, getSiteDirectorName } from "@/lib/taskStorage";
import type { CQIMeetingRecord, CQIAttendee, CqiMeetingSummary } from "@shared/schema";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { History } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  CheckCircle2,
  ClipboardList,
  Building2,
  FileDown,
  Save,
  UserCheck,
  PenLine,
  AlertCircle,
  Mail,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

// ── Types ────────────────────────────────────────────────────────────────────

type QuarterOption = "Q1" | "Q2" | "Q3" | "Q4" | "Other" | "";

// ── Helpers ──────────────────────────────────────────────────────────────────

function buildEmptyRecord(siteId: string, quarter: string, siteName: string, pharmacyLocation: string, pic: string): CQIMeetingRecord {
  return {
    siteId,
    quarter,
    siteName,
    pharmacyLocation,
    pic,
    selectedQuarter: "",
    otherDate: "",
    safetyChecks: {
      fireExtinguisher: false,
      smokeDetector: false,
      evacuationPlan: false,
    },
    agendaItems: {
      regulatoryUpdates: false,
      workflowUpdates: false,
      qreIssues: false,
      policyUpdates: false,
      qmcMeetingMinutes: false,
    },
    qreIssues: "",
    actionPlan: "",
    attendees: [],
    status: "not_started",
    lastUpdatedAt: new Date().toISOString(),
  };
}

function formatRole(role: string): string {
  return getRoleLabel(role as Parameters<typeof getRoleLabel>[0]);
}

function StatusBadge({ status }: { status: CQIMeetingRecord["status"] }) {
  if (status === "submitted") {
    return (
      <Badge className="bg-emerald-100 text-emerald-800 border-emerald-200" data-testid="cqi-status-badge">
        <CheckCircle2 className="w-3.5 h-3.5 mr-1" />
        Submitted
      </Badge>
    );
  }
  if (status === "in_progress") {
    return (
      <Badge className="bg-amber-100 text-amber-800 border-amber-200" data-testid="cqi-status-badge">
        In Progress
      </Badge>
    );
  }
  return (
    <Badge variant="secondary" data-testid="cqi-status-badge">
      Not Started
    </Badge>
  );
}

// ── Shared PDF page styles ───────────────────────────────────────────────────

const PAGE_STYLE: React.CSSProperties = {
  position: "absolute",
  left: "-9999px",
  top: 0,
  width: "816px",
  minHeight: "1056px",
  fontFamily: "Arial, sans-serif",
  fontSize: "12px",
  color: "#000",
  background: "#fff",
  padding: "40px",
  boxSizing: "border-box",
};

const SECTION_HEADER: React.CSSProperties = {
  fontWeight: "bold",
  fontSize: "13px",
  backgroundColor: "#eff6ff",
  padding: "6px 10px",
  marginBottom: "8px",
  borderLeft: "3px solid #1e40af",
};

function PageHeader({ record }: { record: CQIMeetingRecord }) {
  return (
    <>
      <div style={{ textAlign: "center", marginBottom: "24px" }}>
        <div style={{ fontSize: "18px", fontWeight: "bold", color: "#1e40af" }}>
          AHF / Pharmacy4Humanity
        </div>
        <div style={{ fontSize: "16px", fontWeight: "bold", marginTop: "4px" }}>
          CQI-QRE Quarterly Meeting Form
        </div>
        <div style={{ fontSize: "11px", color: "#6b7280", marginTop: "2px" }}>
          Continuous Quality Improvement — Quality-Related Event Documentation
        </div>
      </div>
      <div style={{ borderBottom: "2px solid #1e40af", marginBottom: "20px" }} />
    </>
  );
}

function PageFooter({ record, page }: { record: CQIMeetingRecord; page: number }) {
  return (
    <div style={{ marginTop: "32px", borderTop: "1px solid #d1d5db", paddingTop: "12px", display: "flex", justifyContent: "space-between", color: "#9ca3af", fontSize: "10px" }}>
      <span>Generated by Koheez.ai · {record.quarter} · Site {record.siteId}</span>
      <span>{new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })} · Page {page} of 2</span>
    </div>
  );
}

// ── PDF Page 1: form details ──────────────────────────────────────────────────

function PrintPage1({
  record,
  page1Ref,
}: {
  record: CQIMeetingRecord;
  page1Ref: React.RefObject<HTMLDivElement>;
}) {
  return (
    <div ref={page1Ref} style={PAGE_STYLE}>
      <PageHeader record={record} />

      {/* Pharmacy info */}
      <table style={{ width: "100%", marginBottom: "20px", borderCollapse: "collapse" }}>
        <tbody>
          <tr>
            <td style={{ width: "50%", paddingRight: "16px", paddingBottom: "8px" }}>
              <span style={{ fontWeight: "bold" }}>Pharmacy Location: </span>
              <span style={{ borderBottom: "1px solid #000", display: "inline-block", minWidth: "160px", paddingBottom: "2px" }}>
                {record.pharmacyLocation || ""}
              </span>
            </td>
            <td style={{ width: "50%" }}>
              <span style={{ fontWeight: "bold" }}>PIC: </span>
              <span style={{ borderBottom: "1px solid #000", display: "inline-block", minWidth: "160px", paddingBottom: "2px" }}>
                {record.pic || ""}
              </span>
            </td>
          </tr>
          <tr>
            <td colSpan={2} style={{ paddingBottom: "8px" }}>
              <span style={{ fontWeight: "bold" }}>Date (Quarter): </span>
              {(["Q1", "Q2", "Q3", "Q4", "Other"] as const).map((q) => (
                <span key={q} style={{ marginRight: "16px" }}>
                  <span style={{
                    display: "inline-block",
                    width: "12px",
                    height: "12px",
                    border: "1px solid #000",
                    borderRadius: "2px",
                    backgroundColor: record.selectedQuarter === q ? "#1e40af" : "transparent",
                    verticalAlign: "middle",
                    marginRight: "4px",
                  }} />
                  {q}
                </span>
              ))}
              {record.selectedQuarter === "Other" && record.otherDate && (
                <span style={{ marginLeft: "4px" }}>({record.otherDate})</span>
              )}
            </td>
          </tr>
        </tbody>
      </table>

      {/* Safety checks */}
      <div style={{ marginBottom: "20px" }}>
        <div style={SECTION_HEADER}>Safety Checks</div>
        {[
          { key: "fireExtinguisher" as const, label: "Fire Extinguisher Expiration Date Checked" },
          { key: "smokeDetector" as const, label: "Smoke Detector Expiration Date Checked" },
          { key: "evacuationPlan" as const, label: "Evacuation Plan Reviewed" },
        ].map(({ key, label }) => (
          <div key={key} style={{ display: "flex", alignItems: "center", marginBottom: "6px", paddingLeft: "10px" }}>
            <span style={{
              display: "inline-block",
              width: "14px",
              height: "14px",
              border: "1px solid #000",
              borderRadius: "2px",
              backgroundColor: record.safetyChecks[key] ? "#1e40af" : "transparent",
              marginRight: "8px",
              flexShrink: 0,
            }} />
            <span>{label}</span>
          </div>
        ))}
      </div>

      {/* Agenda items */}
      <div style={{ marginBottom: "20px" }}>
        <div style={SECTION_HEADER}>Agenda Items</div>
        {[
          { key: "regulatoryUpdates" as const, label: "Regulatory Updates / Issues" },
          { key: "workflowUpdates" as const, label: "Workflow Updates / Issues" },
          { key: "qreIssues" as const, label: "QRE Issues" },
          { key: "policyUpdates" as const, label: "Policy and Procedure Updates" },
          { key: "qmcMeetingMinutes" as const, label: "QMC Meeting Minutes and Reports" },
        ].map(({ key, label }) => (
          <div key={key} style={{ display: "flex", alignItems: "center", marginBottom: "6px", paddingLeft: "10px" }}>
            <span style={{
              display: "inline-block",
              width: "14px",
              height: "14px",
              border: "1px solid #000",
              borderRadius: "2px",
              backgroundColor: record.agendaItems[key] ? "#1e40af" : "transparent",
              marginRight: "8px",
              flexShrink: 0,
            }} />
            <span>{label}</span>
          </div>
        ))}
      </div>

      {/* QRE issues */}
      <div style={{ marginBottom: "20px" }}>
        <div style={SECTION_HEADER}>QRE Issues Discussed</div>
        <div style={{
          border: "1px solid #d1d5db",
          borderRadius: "4px",
          minHeight: "100px",
          padding: "8px 12px",
          whiteSpace: "pre-wrap",
          lineHeight: "1.5",
          color: record.qreIssues ? "#000" : "#9ca3af",
        }}>
          {record.qreIssues || "No issues documented."}
        </div>
      </div>

      {/* Action plan */}
      <div style={{ marginBottom: "24px" }}>
        <div style={SECTION_HEADER}>QRE Action Plan / Process Changes / Suggestions from Staff</div>
        <div style={{
          border: "1px solid #d1d5db",
          borderRadius: "4px",
          minHeight: "100px",
          padding: "8px 12px",
          whiteSpace: "pre-wrap",
          lineHeight: "1.5",
          color: record.actionPlan ? "#000" : "#9ca3af",
        }}>
          {record.actionPlan || "No action plan documented."}
        </div>
      </div>

      <PageFooter record={record} page={1} />
    </div>
  );
}

// ── PDF Page 2: attendance ───────────────────────────────────────────────────

function PrintPage2({
  record,
  page2Ref,
}: {
  record: CQIMeetingRecord;
  page2Ref: React.RefObject<HTMLDivElement>;
}) {
  const blankRows = Math.max(0, 12 - record.attendees.length);
  return (
    <div ref={page2Ref} style={PAGE_STYLE}>
      <PageHeader record={record} />

      <div style={{ marginBottom: "8px", fontSize: "13px", color: "#374151" }}>
        <span style={{ fontWeight: "bold" }}>Pharmacy: </span>{record.pharmacyLocation || "—"}
        <span style={{ marginLeft: "24px", fontWeight: "bold" }}>Quarter: </span>{record.selectedQuarter || "—"}
      </div>

      <div style={SECTION_HEADER}>Meeting Attendance — Print Name &amp; Signature</div>

      <table style={{ width: "100%", borderCollapse: "collapse", marginTop: "8px" }}>
        <thead>
          <tr style={{ backgroundColor: "#dbeafe" }}>
            <th style={{ border: "1px solid #93c5fd", padding: "8px 12px", textAlign: "left", width: "5%" }}>#</th>
            <th style={{ border: "1px solid #93c5fd", padding: "8px 12px", textAlign: "left", width: "28%" }}>Print Name</th>
            <th style={{ border: "1px solid #93c5fd", padding: "8px 12px", textAlign: "left", width: "18%" }}>Role</th>
            <th style={{ border: "1px solid #93c5fd", padding: "8px 12px", textAlign: "left", width: "32%" }}>Signature</th>
            <th style={{ border: "1px solid #93c5fd", padding: "8px 12px", textAlign: "left", width: "17%" }}>Date / Time</th>
          </tr>
        </thead>
        <tbody>
          {record.attendees.map((att, idx) => (
            <tr key={att.id} style={{ backgroundColor: idx % 2 === 0 ? "#fff" : "#f9fafb" }}>
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px" }}>{idx + 1}</td>
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px", fontWeight: "500" }}>{att.printName}</td>
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px", color: "#6b7280", fontSize: "11px" }}>{formatRole(att.role)}</td>
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px", fontStyle: "italic", fontFamily: "Georgia, serif", fontSize: "14px", color: "#1e3a8a" }}>
                {att.signatureName}
              </td>
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px", color: "#6b7280", fontSize: "10px" }}>
                {new Date(att.signedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                {" · "}
                {new Date(att.signedAt).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}
              </td>
            </tr>
          ))}
          {Array.from({ length: blankRows }).map((_, idx) => (
            <tr key={`blank-${idx}`} style={{ backgroundColor: (record.attendees.length + idx) % 2 === 0 ? "#fff" : "#f9fafb" }}>
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px", color: "#9ca3af" }}>{record.attendees.length + idx + 1}</td>
              <td style={{ border: "1px solid #d1d5db", padding: "22px 12px" }} />
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px" }} />
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px" }} />
              <td style={{ border: "1px solid #d1d5db", padding: "7px 12px" }} />
            </tr>
          ))}
        </tbody>
      </table>

      <PageFooter record={record} page={2} />
    </div>
  );
}

// ── Sign Attendance Modal ─────────────────────────────────────────────────────

function SignAttendanceModal({
  open,
  onClose,
  onSign,
  defaultName,
}: {
  open: boolean;
  onClose: () => void;
  onSign: (name: string) => void;
  defaultName: string;
}) {
  const [name, setName] = useState(defaultName);

  useEffect(() => {
    if (open) setName(defaultName);
  }, [open, defaultName]);

  function handleConfirm() {
    if (!name.trim()) return;
    onSign(name.trim());
    onClose();
  }

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onClose(); }}>
      <DialogContent className="max-w-md" data-testid="sign-modal" aria-describedby="sign-modal-desc">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <PenLine className="w-4 h-4 text-blue-600" />
            Sign Meeting Attendance
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-2">
          <p id="sign-modal-desc" className="text-sm text-muted-foreground leading-relaxed">
            By typing your full name below and clicking <strong>Confirm Signature</strong>, you
            are electronically signing the CQI-QRE Quarterly Meeting attendance record. This
            constitutes your consent and attestation of attendance.
          </p>
          <div className="space-y-1.5">
            <Label htmlFor="sign-name" className="text-sm font-medium">
              Full Name (as it should appear on record)
            </Label>
            <Input
              id="sign-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Enter your full name"
              onKeyDown={(e) => { if (e.key === "Enter") handleConfirm(); }}
              data-testid="sign-name-input"
            />
          </div>
          {name.trim() && (
            <div className="rounded-md border bg-muted/30 px-4 py-3">
              <p className="text-xs text-muted-foreground mb-1">Signature preview</p>
              <p className="text-lg italic" style={{ fontFamily: "Georgia, serif", color: "#1e3a8a" }}>
                {name.trim()}
              </p>
            </div>
          )}
        </div>
        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={onClose} data-testid="sign-cancel-btn">
            Cancel
          </Button>
          <Button
            onClick={handleConfirm}
            disabled={!name.trim()}
            data-testid="sign-confirm-btn"
          >
            <UserCheck className="w-4 h-4 mr-2" />
            Confirm Signature
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ── Email Team to Sign Modal ──────────────────────────────────────────────────

function EmailTeamModal({
  open,
  onClose,
  staff,
  currentEmail,
  quarter,
  siteId,
  signedEmails,
}: {
  open: boolean;
  onClose: () => void;
  staff: StoreStaffMember[];
  currentEmail: string;
  quarter: string;
  siteId: string;
  signedEmails: string[];
}) {
  const { toast } = useToast();
  const [selected, setSelected] = useState<Record<string, boolean>>({});
  const [sending, setSending] = useState(false);

  // Everyone on the store roster except the director sending the request.
  const recipients = staff.filter(
    (m) => m.email.toLowerCase() !== currentEmail.toLowerCase()
  );
  const signedSet = new Set(signedEmails.map((e) => e.toLowerCase()));

  useEffect(() => {
    if (open) {
      const init: Record<string, boolean> = {};
      // Pre-select those who have NOT yet signed.
      recipients.forEach((m) => {
        init[m.email] = !signedSet.has(m.email.toLowerCase());
      });
      setSelected(init);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  const chosen = recipients.filter((m) => selected[m.email]);

  async function handleSend() {
    if (chosen.length === 0) return;
    setSending(true);
    try {
      const result = await apiRequest<{
        configured: boolean;
        sent: number;
        failed: number;
        total: number;
      }>("/api/cqi/email-signers", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          emails: chosen.map((m) => m.email),
          quarter,
          siteId,
        }),
      });

      if (!result.configured) {
        toast({
          title: "Email not set up",
          description:
            "Email sending isn't configured yet. Ask your administrator to connect Outlook before sending sign requests.",
          variant: "destructive",
        });
      } else if (result.sent > 0) {
        toast({
          title: "Sign requests sent",
          description: `Emailed ${result.sent} team member${result.sent === 1 ? "" : "s"}.${
            result.failed ? ` ${result.failed} could not be sent.` : ""
          }`,
        });
        onClose();
      } else {
        toast({
          title: "Could not send",
          description: "No emails were sent. Please try again.",
          variant: "destructive",
        });
      }
    } catch (err) {
      toast({
        title: "Error",
        description: "Failed to send sign requests. Please try again.",
        variant: "destructive",
      });
    } finally {
      setSending(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onClose(); }}>
      <DialogContent className="max-w-md" data-testid="email-team-modal" aria-describedby="email-team-desc">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Mail className="w-4 h-4 text-blue-600" />
            Email Team to Sign
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-2">
          <p id="email-team-desc" className="text-sm text-muted-foreground leading-relaxed">
            Select the team members to email. Each person receives a link to sign the
            CQI-QRE Quarterly Meeting attendance record.
          </p>
          {recipients.length === 0 ? (
            <div className="rounded-md border border-dashed p-6 text-center text-sm text-muted-foreground" data-testid="email-team-empty">
              No other team members are listed for this store.
            </div>
          ) : (
            <div className="space-y-1 max-h-72 overflow-y-auto pr-1">
              {recipients.map((m) => {
                const hasSigned = signedSet.has(m.email.toLowerCase());
                return (
                  <label
                    key={m.email}
                    className="flex items-center gap-3 rounded-md px-2 py-2 hover-elevate cursor-pointer"
                    data-testid={`email-team-row-${m.email}`}
                  >
                    <Checkbox
                      checked={!!selected[m.email]}
                      onCheckedChange={(val) =>
                        setSelected((prev) => ({ ...prev, [m.email]: !!val }))
                      }
                      data-testid={`email-team-checkbox-${m.email}`}
                    />
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-sm font-medium text-foreground truncate">{m.name}</span>
                        {hasSigned && (
                          <Badge className="bg-emerald-100 text-emerald-800 border-emerald-200">
                            <CheckCircle2 className="w-3 h-3 mr-1" />
                            Signed
                          </Badge>
                        )}
                      </div>
                      <div className="text-xs text-muted-foreground truncate">
                        {getRoleLabel(m.role)} · {m.email}
                      </div>
                    </div>
                  </label>
                );
              })}
            </div>
          )}
        </div>
        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={onClose} data-testid="email-team-cancel-btn">
            Cancel
          </Button>
          <Button
            onClick={handleSend}
            disabled={chosen.length === 0 || sending}
            data-testid="email-team-send-btn"
          >
            <Mail className="w-4 h-4 mr-2" />
            {sending ? "Sending…" : `Send to ${chosen.length || ""}`.trim()}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ── Main page ────────────────────────────────────────────────────────────────

export default function CQIMeeting() {
  const { user } = useAuth();
  const { toast } = useToast();
  const profile = user ? getUserProfile(user.email, user.name ?? "") : null;

  const currentQuarter = getCurrentQuarter();
  const [selectedQuarter, setSelectedQuarter] = useState(currentQuarter);
  const quarter = selectedQuarter;
  const isViewingPast = selectedQuarter !== currentQuarter;
  const siteId = profile?.siteId ?? "";
  const isViewer = profile ? isRegionalOrAbove(profile.role) : false;

  const isDirectorOrAbove = profile ? isDirectorRole(profile.role) : false;
  const isTech = profile ? isTechRole(profile.role) : false;
  // Directors edit the current quarter only. Past quarters are always
  // read-only (back-dating is out of scope) for everyone.
  const canEdit = isDirectorOrAbove && !isViewingPast;
  // Every staff member assigned to the site can view the meeting form
  // (current or any archived quarter) read-only. Editing remains gated by
  // canEdit (directors, current quarter only). The server already restricts
  // who can fetch a site's records, so reaching here means the user is
  // authorized to view this site.
  const canViewForm = true;

  const [signModalOpen, setSignModalOpen] = useState(false);
  const [emailModalOpen, setEmailModalOpen] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const page1Ref = useRef<HTMLDivElement>(null);
  const page2Ref = useRef<HTMLDivElement>(null);

  // Server-stored record, shared across every user at the site.
  const meetingQueryKey = ["/api/cqi", siteId, "meeting", quarter] as const;
  const { data: serverRecord, isLoading } = useQuery<CQIMeetingRecord | null>({
    queryKey: meetingQueryKey,
    queryFn: () =>
      apiRequest<CQIMeetingRecord | null>(
        `/api/cqi/${encodeURIComponent(siteId)}/meeting?quarter=${encodeURIComponent(quarter)}`,
      ),
    enabled: !!siteId && !!quarter,
  });

  // Archive: every saved meeting for this site (newest first). Shared across
  // all roles — staff, techs and directors can browse prior quarters.
  const listQueryKey = ["/api/cqi", siteId, "meetings"] as const;
  const { data: meetingList } = useQuery<CqiMeetingSummary[]>({
    queryKey: listQueryKey,
    queryFn: () =>
      apiRequest<CqiMeetingSummary[]>(
        `/api/cqi/${encodeURIComponent(siteId)}/meetings`,
      ),
    enabled: !!siteId,
  });

  // Quarter options for the archive selector: the current quarter is always
  // available (so the user can return to it) plus any saved past quarters.
  const quarterOptions = useMemo(() => {
    const map = new Map<string, CqiMeetingSummary | null>();
    map.set(currentQuarter, null);
    for (const m of meetingList ?? []) {
      if (!map.has(m.quarter)) map.set(m.quarter, m);
      else if (m.quarter !== currentQuarter) map.set(m.quarter, m);
    }
    return Array.from(map.entries())
      .sort((a, b) => b[0].localeCompare(a[0]))
      .map(([q, summary]) => ({ quarter: q, summary }));
  }, [meetingList, currentQuarter]);

  // Local editable copy. Directors edit fields locally and persist via Save;
  // everyone else sees this as a read-only mirror of the server record.
  // The draft is seeded ONCE per site/quarter so that later server updates
  // (e.g. an attendance signature refreshing the query cache) never clobber a
  // director's unsaved field edits. Attendees are always read live from the
  // server record below.
  const [draft, setDraft] = useState<CQIMeetingRecord | null>(null);
  const loadedKeyRef = useRef<string | null>(null);
  useEffect(() => {
    if (!siteId || !quarter) return;
    const key = `${siteId}|${quarter}`;
    if (loadedKeyRef.current === key) return;
    if (serverRecord) {
      setDraft(serverRecord);
      loadedKeyRef.current = key;
    } else if (!isLoading) {
      setDraft(
        buildEmptyRecord(
          siteId,
          quarter,
          profile?.siteName ?? "",
          profile?.siteName ?? "",
          getSiteDirectorName(siteId),
        ),
      );
      loadedKeyRef.current = key;
    }
  }, [serverRecord, isLoading, siteId, quarter]);

  // The attendance list always reflects the latest server state so signatures
  // from other users appear without a manual refresh.
  const record: CQIMeetingRecord | null = draft
    ? { ...draft, attendees: serverRecord?.attendees ?? draft.attendees }
    : null;

  const saveMutation = useMutation({
    mutationFn: (data: CQIMeetingRecord) => {
      const { attendees, status, lastUpdatedAt, submittedBy, submittedAt, ...payload } = data;
      return apiRequest<CQIMeetingRecord>(
        `/api/cqi/${encodeURIComponent(siteId)}/meeting`,
        { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) },
      );
    },
    onSuccess: (saved) => {
      queryClient.setQueryData(meetingQueryKey, saved);
      queryClient.invalidateQueries({ queryKey: listQueryKey });
      setDraft(saved);
      toast({ title: "Saved", description: "Meeting form saved successfully." });
    },
    onError: () => {
      toast({ title: "Save failed", description: "Could not save the meeting form. Please try again.", variant: "destructive" });
    },
  });

  const signMutation = useMutation({
    mutationFn: (fullName: string) =>
      apiRequest<CQIMeetingRecord>(
        `/api/cqi/${encodeURIComponent(siteId)}/meeting/sign?quarter=${encodeURIComponent(quarter)}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            printName: fullName,
            signatureName: fullName,
            siteName: profile?.siteName ?? "",
            pharmacyLocation: record?.pharmacyLocation ?? profile?.siteName ?? "",
          }),
        },
      ),
    onSuccess: (saved) => {
      queryClient.setQueryData(meetingQueryKey, saved);
      queryClient.invalidateQueries({ queryKey: listQueryKey });
      toast({ title: "Signed", description: "Your attendance has been recorded." });
    },
    onError: () => {
      toast({ title: "Sign failed", description: "Could not record your signature. Please try again.", variant: "destructive" });
    },
  });

  const isSaving = saveMutation.isPending;

  // ── Field handlers (directors only; local edits persisted on Save) ──

  function setField<K extends keyof CQIMeetingRecord>(key: K, val: CQIMeetingRecord[K]) {
    if (!draft || !canEdit) return;
    setDraft({ ...draft, [key]: val });
  }

  function setSafetyCheck(key: keyof CQIMeetingRecord["safetyChecks"], val: boolean) {
    if (!draft || !canEdit) return;
    setDraft({ ...draft, safetyChecks: { ...draft.safetyChecks, [key]: val } });
  }

  function setAgendaItem(key: keyof CQIMeetingRecord["agendaItems"], val: boolean) {
    if (!draft || !canEdit) return;
    setDraft({ ...draft, agendaItems: { ...draft.agendaItems, [key]: val } });
  }

  function handleSave() {
    if (!record || !canEdit) return;
    saveMutation.mutate(record);
  }

  // ── Sign attendance ──

  function alreadySigned(): boolean {
    if (!record || !user) return false;
    return record.attendees.some((a) => a.userEmail === user.email);
  }

  function handleSign(fullName: string) {
    if (!profile || !user) return;
    signMutation.mutate(fullName);
  }

  // ── PDF export (two-page controlled layout) ──

  async function handleExportPDF() {
    if (!record || !page1Ref.current || !page2Ref.current) return;
    setIsExporting(true);
    try {
      const canvasOpts = { scale: 2, useCORS: true, backgroundColor: "#ffffff", logging: false };
      const [canvas1, canvas2] = await Promise.all([
        html2canvas(page1Ref.current, canvasOpts),
        html2canvas(page2Ref.current, canvasOpts),
      ]);

      const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      const addCanvasToPage = (canvas: HTMLCanvasElement) => {
        const imgData = canvas.toDataURL("image/jpeg", 0.95);
        const imgAspect = canvas.height / canvas.width;
        const imgWidth = pageWidth;
        const imgHeight = imgAspect * imgWidth;
        const yOffset = Math.max(0, (pageHeight - imgHeight) / 2);
        pdf.addImage(imgData, "JPEG", 0, yOffset, imgWidth, Math.min(imgHeight, pageHeight));
      };

      addCanvasToPage(canvas1);
      pdf.addPage();
      addCanvasToPage(canvas2);

      const filename = `CQI-QRE-Meeting-${record.quarter}-${record.siteId}.pdf`;
      pdf.save(filename);
      toast({ title: "PDF exported", description: `Saved as ${filename}` });
    } catch (err) {
      console.error("PDF export error:", err);
      toast({ title: "Export failed", description: "Could not generate PDF. Please try again.", variant: "destructive" });
    } finally {
      setIsExporting(false);
    }
  }

  if (!record) {
    return (
      <div className="flex items-center justify-center h-48 text-muted-foreground" data-testid="cqi-loading">
        <ClipboardList className="w-5 h-5 mr-2 animate-pulse" />
        Loading…
      </div>
    );
  }

  const signed = alreadySigned();

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6" data-testid="cqi-meeting-page">

      {/* Hidden two-page print layout for PDF export */}
      <PrintPage1 record={record} page1Ref={page1Ref} />
      <PrintPage2 record={record} page2Ref={page2Ref} />

      {/* Page header */}
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-md bg-blue-50">
            <ClipboardList className="w-5 h-5 text-blue-600" />
          </div>
          <div>
            <h1 className="text-xl font-semibold text-foreground">CQI-QRE Quarterly Meeting</h1>
            <p className="text-sm text-muted-foreground">
              Continuous Quality Improvement — {quarter}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          {!isTech && <StatusBadge status={record.status} />}
          {canEdit && (
            <Button
              variant="outline"
              onClick={handleSave}
              disabled={isSaving}
              data-testid="cqi-save-btn"
            >
              <Save className="w-4 h-4 mr-2" />
              {isSaving ? "Saving…" : "Save"}
            </Button>
          )}
          {/* Any staff member (including technicians) can export the PDF, for
              the current quarter or any saved prior meeting. */}
          <Button
            variant="outline"
            onClick={handleExportPDF}
            disabled={isExporting}
            data-testid="cqi-export-btn"
          >
            <FileDown className="w-4 h-4 mr-2" />
            {isExporting ? "Exporting…" : "Export PDF"}
          </Button>
        </div>
      </div>

      {/* Prior meetings archive selector */}
      {quarterOptions.length > 1 && (
        <div
          className="rounded-md border p-4 flex flex-wrap items-center gap-3"
          data-testid="cqi-archive-selector"
        >
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <History className="w-4 h-4" />
            <span>Prior meetings</span>
          </div>
          <Select
            value={selectedQuarter}
            onValueChange={(val) => setSelectedQuarter(val)}
          >
            <SelectTrigger className="w-[260px]" data-testid="cqi-archive-select-trigger">
              <SelectValue placeholder="Select a quarter" />
            </SelectTrigger>
            <SelectContent>
              {quarterOptions.map(({ quarter: q, summary }) => (
                <SelectItem key={q} value={q} data-testid={`cqi-archive-option-${q}`}>
                  {q}
                  {q === currentQuarter ? " (current)" : ""}
                  {summary?.lastUpdatedAt
                    ? ` — updated ${new Date(summary.lastUpdatedAt).toLocaleDateString()}`
                    : ""}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {isViewingPast && (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setSelectedQuarter(currentQuarter)}
              data-testid="cqi-archive-back-current"
            >
              Back to current quarter
            </Button>
          )}
        </div>
      )}

      {/* Read-only notice when viewing a past quarter */}
      {isViewingPast && (
        <div
          className="rounded-md bg-muted px-4 py-3 flex items-start gap-3"
          data-testid="cqi-past-notice"
        >
          <History className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5" />
          <p className="text-sm text-muted-foreground">
            You are viewing a saved meeting from {selectedQuarter}. Past meetings are
            read-only — you can review and export them, but not edit them.
          </p>
        </div>
      )}

      {/* Site label */}
      {profile && (
        <div className="flex items-center gap-2 text-sm text-muted-foreground" data-testid="cqi-site-label">
          <Building2 className="w-4 h-4" />
          <span>{profile.siteName} — Site {profile.siteId}</span>
        </div>
      )}

      {/* Read-only notice for non-editors (non-tech, non-director staff) */}
      {!canEdit && !isViewer && !isTech && !isViewingPast && (
        <div className="rounded-md bg-amber-50 border border-amber-200 px-4 py-3 flex items-start gap-3" data-testid="cqi-readonly-notice">
          <AlertCircle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
          <p className="text-sm text-amber-800">
            You can sign the attendance list below. Only directors can edit the rest of the form.
          </p>
        </div>
      )}

      {/* Tech-role notice */}
      {isTech && !isViewingPast && (
        <div className="rounded-md bg-blue-50 border border-blue-200 px-4 py-3 flex items-start gap-3" data-testid="cqi-tech-notice">
          <AlertCircle className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
          <p className="text-sm text-blue-800">
            You can review the meeting details below and sign the attendance list to confirm your participation. Only directors can edit the form.
          </p>
        </div>
      )}

      {/* ── Section 1: Header info ── */}
      {canViewForm && (
        <div className="rounded-md border p-5 space-y-4" data-testid="cqi-header-section">
          <h2 className="text-sm font-semibold text-foreground">Meeting Information</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label htmlFor="pharmacy-location" className="text-xs text-muted-foreground">
                Pharmacy Location
              </Label>
              <Input
                id="pharmacy-location"
                value={record.pharmacyLocation}
                onChange={(e) => setField("pharmacyLocation", e.target.value)}
                readOnly={!canEdit}
                placeholder="e.g. AHF Pharmacy — Hollywood"
                data-testid="cqi-pharmacy-location"
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="cqi-pic" className="text-xs text-muted-foreground">
                PIC (Pharmacist-in-Charge)
              </Label>
              <Input
                id="cqi-pic"
                value={record.pic}
                onChange={(e) => setField("pic", e.target.value)}
                readOnly={!canEdit}
                placeholder="Pharmacist full name"
                data-testid="cqi-pic"
              />
            </div>
          </div>

          {/* Quarter selection */}
          <div className="space-y-2">
            <Label className="text-xs text-muted-foreground">Quarter / Period</Label>
            <div className="flex flex-wrap gap-2">
              {(["Q1", "Q2", "Q3", "Q4", "Other"] as QuarterOption[]).map((q) => (
                <Button
                  key={q}
                  type="button"
                  variant={record.selectedQuarter === q ? "default" : "outline"}
                  onClick={() => canEdit && setField("selectedQuarter", q as QuarterOption)}
                  disabled={!canEdit}
                  data-testid={`cqi-quarter-${q}`}
                  aria-pressed={record.selectedQuarter === q}
                >
                  {q}
                </Button>
              ))}
            </div>
            {record.selectedQuarter === "Other" && (
              <div className="mt-2 max-w-xs space-y-1.5">
                <Label htmlFor="other-date" className="text-xs text-muted-foreground">
                  Specify date / period
                </Label>
                <Input
                  id="other-date"
                  value={record.otherDate}
                  onChange={(e) => setField("otherDate", e.target.value)}
                  readOnly={!canEdit}
                  placeholder="e.g. January 15, 2026"
                  data-testid="cqi-other-date"
                />
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Section 2: Safety Checks ── */}
      {canViewForm && (
        <div className="rounded-md border p-5 space-y-4" data-testid="cqi-safety-section">
          <h2 className="text-sm font-semibold text-foreground">Safety Checks</h2>
          <div className="space-y-3">
            {[
              { key: "fireExtinguisher" as const, label: "Fire Extinguisher Expiration Date Checked" },
              { key: "smokeDetector" as const, label: "Smoke Detector Expiration Date Checked" },
              { key: "evacuationPlan" as const, label: "Evacuation Plan Reviewed" },
            ].map(({ key, label }) => (
              <div key={key} className="flex items-center gap-3" data-testid={`cqi-safety-${key}`}>
                <Checkbox
                  id={`safety-${key}`}
                  checked={record.safetyChecks[key]}
                  disabled={!canEdit}
                  onCheckedChange={(val) => setSafetyCheck(key, !!val)}
                  data-testid={`cqi-safety-checkbox-${key}`}
                />
                <Label
                  htmlFor={`safety-${key}`}
                  className={`text-sm select-none ${!canEdit ? "cursor-default" : "cursor-pointer"} ${
                    record.safetyChecks[key] ? "line-through text-muted-foreground" : "text-foreground"
                  }`}
                >
                  {label}
                </Label>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Section 3: Agenda Items ── */}
      {canViewForm && (
        <div className="rounded-md border p-5 space-y-4" data-testid="cqi-agenda-section">
          <h2 className="text-sm font-semibold text-foreground">Agenda Items</h2>
          <div className="space-y-3">
            {[
              { key: "regulatoryUpdates" as const, label: "Regulatory Updates / Issues" },
              { key: "workflowUpdates" as const, label: "Workflow Updates / Issues" },
              { key: "qreIssues" as const, label: "QRE Issues" },
              { key: "policyUpdates" as const, label: "Policy and Procedure Updates" },
              { key: "qmcMeetingMinutes" as const, label: "QMC Meeting Minutes and Reports" },
            ].map(({ key, label }) => (
              <div key={key} className="flex items-center gap-3" data-testid={`cqi-agenda-${key}`}>
                <Checkbox
                  id={`agenda-${key}`}
                  checked={record.agendaItems[key]}
                  disabled={!canEdit}
                  onCheckedChange={(val) => setAgendaItem(key, !!val)}
                  data-testid={`cqi-agenda-checkbox-${key}`}
                />
                <Label
                  htmlFor={`agenda-${key}`}
                  className={`text-sm select-none ${!canEdit ? "cursor-default" : "cursor-pointer"} ${
                    record.agendaItems[key] ? "line-through text-muted-foreground" : "text-foreground"
                  }`}
                >
                  {label}
                </Label>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Section 4: QRE Documentation ── */}
      {canViewForm && (
        <div className="rounded-md border p-5 space-y-4" data-testid="cqi-qre-section">
          <h2 className="text-sm font-semibold text-foreground">QRE Documentation</h2>
          <div className="space-y-1.5">
            <Label htmlFor="qre-issues" className="text-xs text-muted-foreground">
              QRE Issues Discussed
            </Label>
            <Textarea
              id="qre-issues"
              value={record.qreIssues}
              onChange={(e) => setField("qreIssues", e.target.value)}
              readOnly={!canEdit}
              placeholder={canEdit ? "Describe quality-related events discussed during this meeting…" : "No issues documented."}
              className="text-sm resize-none min-h-[96px]"
              data-testid="cqi-qre-issues"
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="action-plan" className="text-xs text-muted-foreground">
              QRE Action Plan / Process Changes / Suggestions from Staff
            </Label>
            <Textarea
              id="action-plan"
              value={record.actionPlan}
              onChange={(e) => setField("actionPlan", e.target.value)}
              readOnly={!canEdit}
              placeholder={canEdit ? "Describe action plans, process changes, and staff suggestions…" : "No action plan documented."}
              className="text-sm resize-none min-h-[96px]"
              data-testid="cqi-action-plan"
            />
          </div>
        </div>
      )}

      {/* ── Section 5: Meeting Attendance ── */}
      <div className="rounded-md border p-5 space-y-4" data-testid="cqi-attendance-section">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <h2 className="text-sm font-semibold text-foreground">Meeting Attendance</h2>
          <div className="flex items-center gap-2 flex-wrap">
            {canEdit && (
              <Button
                variant="outline"
                onClick={() => setEmailModalOpen(true)}
                data-testid="cqi-email-team-btn"
              >
                <Mail className="w-4 h-4 mr-2" />
                Email Team to Sign
              </Button>
            )}
            {!isViewingPast && (
              <Button
                variant={signed ? "outline" : "default"}
                onClick={() => setSignModalOpen(true)}
                disabled={signed}
                data-testid="cqi-sign-btn"
              >
                <PenLine className="w-4 h-4 mr-2" />
                {signed ? "Already Signed" : "Sign Attendance"}
              </Button>
            )}
          </div>
        </div>

        {signed && (
          <div className="flex items-center gap-2 text-sm text-emerald-700 bg-emerald-50 border border-emerald-200 rounded-md px-3 py-2" data-testid="cqi-already-signed-notice">
            <CheckCircle2 className="w-4 h-4 shrink-0" />
            Your signature has been recorded for this meeting.
          </div>
        )}

        {record.attendees.length === 0 ? (
          <div className="rounded-md border border-dashed p-8 text-center text-muted-foreground" data-testid="cqi-attendance-empty">
            <UserCheck className="w-7 h-7 mx-auto mb-2 opacity-40" />
            <p className="text-sm">No attendees have signed yet.</p>
            <p className="text-xs mt-1">Staff can click "Sign Attendance" to add their signature.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm" data-testid="cqi-attendance-table">
              <thead>
                <tr className="border-b bg-muted/30">
                  <th className="text-left px-3 py-2 text-xs font-medium text-muted-foreground w-8">#</th>
                  <th className="text-left px-3 py-2 text-xs font-medium text-muted-foreground">Print Name</th>
                  <th className="text-left px-3 py-2 text-xs font-medium text-muted-foreground">Role</th>
                  <th className="text-left px-3 py-2 text-xs font-medium text-muted-foreground">Signature</th>
                  <th className="text-left px-3 py-2 text-xs font-medium text-muted-foreground">Signed</th>
                </tr>
              </thead>
              <tbody>
                {record.attendees.map((att, idx) => (
                  <tr
                    key={att.id}
                    className="border-b last:border-0 hover-elevate"
                    data-testid={`cqi-attendee-row-${att.id}`}
                  >
                    <td className="px-3 py-2.5 text-muted-foreground text-xs">{idx + 1}</td>
                    <td className="px-3 py-2.5 font-medium text-foreground">{att.printName}</td>
                    <td className="px-3 py-2.5 text-muted-foreground text-xs">{formatRole(att.role)}</td>
                    <td className="px-3 py-2.5">
                      <span
                        className="text-base text-blue-900"
                        style={{ fontFamily: "Georgia, serif", fontStyle: "italic" }}
                        data-testid={`cqi-signature-${att.id}`}
                      >
                        {att.signatureName}
                      </span>
                    </td>
                    <td className="px-3 py-2.5 text-xs text-muted-foreground whitespace-nowrap">
                      {new Date(att.signedAt).toLocaleDateString("en-US", {
                        month: "short",
                        day: "numeric",
                        year: "numeric",
                      })}
                      {" · "}
                      {new Date(att.signedAt).toLocaleTimeString("en-US", {
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Sign Modal */}
      <SignAttendanceModal
        open={signModalOpen}
        onClose={() => setSignModalOpen(false)}
        onSign={handleSign}
        defaultName={profile?.name ?? ""}
      />

      {/* Email Team to Sign Modal (directors only) */}
      {canEdit && (
        <EmailTeamModal
          open={emailModalOpen}
          onClose={() => setEmailModalOpen(false)}
          staff={getStoreStaff(siteId)}
          currentEmail={user?.email ?? ""}
          quarter={record.selectedQuarter || quarter}
          siteId={siteId}
          signedEmails={record.attendees.map((a) => a.userEmail)}
        />
      )}
    </div>
  );
}
