import { useState, useEffect } from "react";
import { ShieldAlert } from "lucide-react";

const STORAGE_KEY = "koheez_waiver_accepted";
const GRADIENT = "linear-gradient(90deg, #3b82f6, #9333ea, #ef4444, #facc15)";

interface AssessorWaiverProps {
  onAccept: () => void;
}

export default function AssessorWaiver({ onAccept }: AssessorWaiverProps) {
  const [checked, setChecked] = useState(false);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (localStorage.getItem(STORAGE_KEY) === "true") {
      onAccept();
    } else {
      setVisible(true);
    }
  }, [onAccept]);

  const handleAccept = () => {
    localStorage.setItem(STORAGE_KEY, "true");
    onAccept();
  };

  if (!visible) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"
      data-testid="waiver-overlay"
    >
      <div className="bg-white rounded-md shadow-xl w-full max-w-2xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="px-8 pt-8 pb-5 border-b border-slate-100 shrink-0">
          <div className="flex items-center gap-3 mb-3">
            <div
              className="w-10 h-10 rounded-md flex items-center justify-center shrink-0"
              style={{ backgroundImage: GRADIENT }}
            >
              <ShieldAlert className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">
                HIV/PrEP Treatment Assessor
              </p>
              <h2 className="text-xl font-bold text-slate-900">
                Clinical Responsibility Agreement
              </h2>
            </div>
          </div>
          <p className="text-sm text-slate-500 leading-relaxed">
            Before accessing this tool you must read and acknowledge the following terms. This agreement must be accepted before any use of the Treatment Assessor.
          </p>
        </div>

        {/* Scrollable body */}
        <div className="overflow-y-auto flex-1 px-8 py-6 space-y-5 text-sm text-slate-700 leading-relaxed">
          <section>
            <h3 className="font-bold text-slate-900 mb-1.5">1. Independent Clinical Judgment Required</h3>
            <p>
              The HIV/PrEP Treatment Assessor is a clinical decision support tool only. All output — including drug interaction alerts, dosing recommendations, AI-generated summaries, and consultation questions — is provided for informational purposes to assist, not replace, your professional assessment. You must apply your own independent clinical judgment to every patient encounter. You must not rely solely on the output of this tool when making clinical decisions.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-1.5">2. Review Obligation</h3>
            <p>
              As the licensed pharmacist of record, you are obligated to thoroughly review all output generated by this tool before acting on it. This includes verifying drug interaction alerts against current evidence-based references, confirming AI-generated clinical summaries for accuracy, and independently assessing the appropriateness of any recommendations for the specific patient.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-1.5">3. Acceptance of Liability</h3>
            <p>
              You accept full professional and legal liability for all clinical decisions made in connection with your use of this tool. Koheez.ai, its developers, and its affiliated organizations expressly disclaim liability for any patient harm, adverse outcome, or professional consequence arising from clinical decisions made using the output of the Treatment Assessor, regardless of whether such output contained errors or omissions.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-1.5">4. Professional Accountability and Disciplinary Risk</h3>
            <p>
              Failure to perform a complete, independent review of all tool output prior to making clinical decisions may constitute a breach of your professional duty of care. You understand that such failure may expose you to disciplinary action by your state Board of Pharmacy, your employer, and other applicable licensing or regulatory authorities, up to and including suspension or revocation of your pharmacy license.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-1.5">5. No Substitute for Clinical References</h3>
            <p>
              This tool does not replace consultation with peer-reviewed clinical references, package inserts, clinical pharmacists with specialized HIV expertise, or the patient's treating physician. When clinical uncertainty exists, you are expected to seek appropriate consultation before making any recommendation or intervention.
            </p>
          </section>
        </div>

        {/* Footer / acceptance */}
        <div className="px-8 py-6 border-t border-slate-100 bg-slate-50 rounded-b-md shrink-0 space-y-4">
          <label
            className="flex items-start gap-3 cursor-pointer"
            data-testid="waiver-checkbox-label"
          >
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              data-testid="waiver-checkbox"
              className="mt-0.5 h-4 w-4 rounded border-slate-300 accent-purple-600 cursor-pointer shrink-0"
            />
            <span className="text-sm text-slate-700 leading-relaxed">
              I have read and understood this agreement. I acknowledge that I must exercise independent clinical judgment, that I am solely responsible for all clinical decisions I make using this tool, and that failure to properly review the tool's output may subject me to professional disciplinary action.
            </span>
          </label>

          <button
            onClick={handleAccept}
            disabled={!checked}
            data-testid="waiver-accept-button"
            className="w-full py-3 rounded-md text-sm font-bold text-white transition-opacity disabled:opacity-40 disabled:cursor-not-allowed"
            style={{ backgroundImage: GRADIENT }}
          >
            Accept &amp; Continue to Treatment Assessor
          </button>
        </div>
      </div>
    </div>
  );
}
