name: aptible

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: koheez.ai
          environment: ahf1417
          username: ${{ secrets.APTIBLEUN }}
          password: ${{ secrets.APTIBLEPW }}
